//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcsEnityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CcsServerEntities : DbContext
    {
        public CcsServerEntities()
            : base("name=CcsServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dataset> datasets { get; set; }
        public virtual DbSet<dataset_field> dataset_field { get; set; }
        public virtual DbSet<dataset_mapset> dataset_mapset { get; set; }
        public virtual DbSet<dataset_record> dataset_record { get; set; }
        public virtual DbSet<dip_batch> dip_batch { get; set; }
        public virtual DbSet<diskgroup> diskgroups { get; set; }
        public virtual DbSet<doc_type_mapping> doc_type_mapping { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<field> fields { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<file_type> file_type { get; set; }
        public virtual DbSet<key_type_mapset> key_type_mapset { get; set; }
        public virtual DbSet<legacy_file_info> legacy_file_info { get; set; }
        public virtual DbSet<max_num_keys> max_num_keys { get; set; }
        public virtual DbSet<metadata> metadatas { get; set; }
        public virtual DbSet<note> notes { get; set; }
        public virtual DbSet<onbase_doc_type> onbase_doc_type { get; set; }
        public virtual DbSet<onbase_document> onbase_document { get; set; }
        public virtual DbSet<onbase_file_info> onbase_file_info { get; set; }
        public virtual DbSet<onbase_key_type> onbase_key_type { get; set; }
        public virtual DbSet<onbase_note> onbase_note { get; set; }
        public virtual DbSet<snapshot> snapshots { get; set; }
    }
}
