//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcsEnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class diskgroup
    {
        public long id { get; set; }
        public int flags { get; set; }
        public int max_fldr_files { get; set; }
        public long max_vol_bytes { get; set; }
        public int next_vol { get; set; }
        public string root_path { get; set; }
        public int default_volume_flags { get; set; }
    }
}
