//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcsEnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_type_mapping
    {
        public short id { get; set; }
        public string lookup_000 { get; set; }
        public string lookup_001 { get; set; }
        public string lookup_002 { get; set; }
        public string lookup_003 { get; set; }
        public string lookup_004 { get; set; }
        public string ob_doc_reason_lookup { get; set; }
        public Nullable<short> key_type_mapset_id { get; set; }
        public Nullable<short> ob_doc_type_id { get; set; }
    
        public virtual key_type_mapset key_type_mapset { get; set; }
        public virtual onbase_doc_type onbase_doc_type { get; set; }
    }
}
