//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcsEnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public document()
        {
            this.dataset_record = new HashSet<dataset_record>();
            this.files = new HashSet<file>();
            this.notes = new HashSet<note>();
            this.onbase_document = new HashSet<onbase_document>();
        }
    
        public long id { get; set; }
        public string legacy_id { get; set; }
        public int phase { get; set; }
        public Nullable<int> exclusion_code { get; set; }
        public Nullable<int> exception_code { get; set; }
        public Nullable<int> dip_batch_id { get; set; }
        public Nullable<long> docset_local_id { get; set; }
        public Nullable<long> docset_remote_id { get; set; }
        public short inventory_history_id { get; set; }
        public Nullable<short> snapshot_id { get; set; }
        public string legacy_source { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataset_record> dataset_record { get; set; }
        public virtual dip_batch dip_batch { get; set; }
        public virtual snapshot snapshot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        public virtual metadata metadata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<note> notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onbase_document> onbase_document { get; set; }
    }
}
