//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcsEnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class key_type_mapset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public key_type_mapset()
        {
            this.dataset_mapset = new HashSet<dataset_mapset>();
            this.doc_type_mapping = new HashSet<doc_type_mapping>();
        }
    
        public short id { get; set; }
        public short metadata_doc_date { get; set; }
        public Nullable<short> col_000 { get; set; }
        public Nullable<short> col_001 { get; set; }
        public Nullable<short> col_002 { get; set; }
        public Nullable<short> col_003 { get; set; }
        public Nullable<short> col_004 { get; set; }
        public Nullable<short> col_005 { get; set; }
        public Nullable<short> col_006 { get; set; }
        public Nullable<short> col_007 { get; set; }
        public Nullable<short> col_008 { get; set; }
        public Nullable<short> col_009 { get; set; }
        public Nullable<short> col_010 { get; set; }
        public Nullable<short> col_011 { get; set; }
        public Nullable<short> col_012 { get; set; }
        public Nullable<short> col_013 { get; set; }
        public Nullable<short> col_014 { get; set; }
        public Nullable<short> col_015 { get; set; }
        public Nullable<short> col_016 { get; set; }
        public Nullable<short> col_017 { get; set; }
        public Nullable<short> col_018 { get; set; }
        public Nullable<short> col_019 { get; set; }
        public Nullable<short> col_020 { get; set; }
        public Nullable<short> col_021 { get; set; }
        public Nullable<short> col_022 { get; set; }
        public Nullable<short> col_023 { get; set; }
        public Nullable<short> col_024 { get; set; }
        public Nullable<short> col_025 { get; set; }
        public Nullable<short> col_026 { get; set; }
        public Nullable<short> col_027 { get; set; }
        public Nullable<short> col_028 { get; set; }
        public Nullable<short> col_029 { get; set; }
        public Nullable<short> col_030 { get; set; }
        public Nullable<short> col_031 { get; set; }
        public Nullable<short> col_032 { get; set; }
        public Nullable<short> col_033 { get; set; }
        public Nullable<short> col_034 { get; set; }
        public Nullable<short> col_035 { get; set; }
        public Nullable<short> col_036 { get; set; }
        public Nullable<short> col_037 { get; set; }
        public Nullable<short> col_038 { get; set; }
        public Nullable<short> col_039 { get; set; }
        public Nullable<short> col_040 { get; set; }
        public Nullable<short> col_041 { get; set; }
        public Nullable<short> col_042 { get; set; }
        public Nullable<short> col_043 { get; set; }
        public Nullable<short> col_044 { get; set; }
        public Nullable<short> col_045 { get; set; }
        public Nullable<short> col_046 { get; set; }
        public Nullable<short> col_047 { get; set; }
        public Nullable<short> col_048 { get; set; }
        public Nullable<short> col_049 { get; set; }
        public Nullable<short> col_050 { get; set; }
        public Nullable<short> col_051 { get; set; }
        public Nullable<short> col_052 { get; set; }
        public Nullable<short> col_053 { get; set; }
        public Nullable<short> col_054 { get; set; }
        public Nullable<short> col_055 { get; set; }
        public Nullable<short> col_056 { get; set; }
        public Nullable<short> col_057 { get; set; }
        public Nullable<short> col_058 { get; set; }
        public Nullable<short> col_059 { get; set; }
        public Nullable<short> col_060 { get; set; }
        public Nullable<short> col_061 { get; set; }
        public Nullable<short> col_062 { get; set; }
        public Nullable<short> col_063 { get; set; }
        public Nullable<short> col_064 { get; set; }
        public Nullable<short> col_065 { get; set; }
        public Nullable<short> col_066 { get; set; }
        public Nullable<short> col_067 { get; set; }
        public Nullable<short> col_068 { get; set; }
        public Nullable<short> col_069 { get; set; }
        public Nullable<short> col_070 { get; set; }
        public Nullable<short> col_071 { get; set; }
        public Nullable<short> col_072 { get; set; }
        public Nullable<short> col_073 { get; set; }
        public Nullable<short> col_074 { get; set; }
        public Nullable<short> col_075 { get; set; }
        public Nullable<short> col_076 { get; set; }
        public Nullable<short> col_077 { get; set; }
        public Nullable<short> col_078 { get; set; }
        public Nullable<short> col_079 { get; set; }
        public Nullable<short> col_080 { get; set; }
        public Nullable<short> col_081 { get; set; }
        public Nullable<short> col_082 { get; set; }
        public Nullable<short> col_083 { get; set; }
        public Nullable<short> col_084 { get; set; }
        public Nullable<short> col_085 { get; set; }
        public Nullable<short> col_086 { get; set; }
        public Nullable<short> col_087 { get; set; }
        public Nullable<short> col_088 { get; set; }
        public Nullable<short> col_089 { get; set; }
        public Nullable<short> col_090 { get; set; }
        public Nullable<short> col_091 { get; set; }
        public Nullable<short> col_092 { get; set; }
        public Nullable<short> col_093 { get; set; }
        public Nullable<short> col_094 { get; set; }
        public Nullable<short> col_095 { get; set; }
        public Nullable<short> col_096 { get; set; }
        public Nullable<short> col_097 { get; set; }
        public Nullable<short> col_098 { get; set; }
        public Nullable<short> col_099 { get; set; }
        public Nullable<short> col_100 { get; set; }
        public Nullable<short> col_101 { get; set; }
        public Nullable<short> col_102 { get; set; }
        public Nullable<short> col_103 { get; set; }
        public Nullable<short> col_104 { get; set; }
        public Nullable<short> col_105 { get; set; }
        public Nullable<short> col_106 { get; set; }
        public Nullable<short> col_107 { get; set; }
        public Nullable<short> col_108 { get; set; }
        public Nullable<short> col_109 { get; set; }
        public Nullable<short> col_110 { get; set; }
        public Nullable<short> col_111 { get; set; }
        public Nullable<short> col_112 { get; set; }
        public Nullable<short> col_113 { get; set; }
        public Nullable<short> col_114 { get; set; }
        public Nullable<short> col_115 { get; set; }
        public Nullable<short> col_116 { get; set; }
        public Nullable<short> col_117 { get; set; }
        public Nullable<short> col_118 { get; set; }
        public Nullable<short> col_119 { get; set; }
        public Nullable<short> col_120 { get; set; }
        public Nullable<short> col_121 { get; set; }
        public Nullable<short> col_122 { get; set; }
        public Nullable<short> col_123 { get; set; }
        public Nullable<short> col_124 { get; set; }
        public Nullable<short> col_125 { get; set; }
        public Nullable<short> col_126 { get; set; }
        public Nullable<short> col_127 { get; set; }
        public string name { get; set; }
        public Nullable<short> col_128 { get; set; }
        public Nullable<short> col_129 { get; set; }
        public Nullable<short> col_130 { get; set; }
        public Nullable<short> col_131 { get; set; }
        public Nullable<short> col_132 { get; set; }
        public Nullable<short> col_133 { get; set; }
        public Nullable<short> col_134 { get; set; }
        public Nullable<short> col_135 { get; set; }
        public Nullable<short> col_136 { get; set; }
        public Nullable<short> col_137 { get; set; }
        public Nullable<short> col_138 { get; set; }
        public Nullable<short> col_139 { get; set; }
        public Nullable<short> col_140 { get; set; }
        public Nullable<short> col_141 { get; set; }
        public Nullable<short> col_142 { get; set; }
        public Nullable<short> col_143 { get; set; }
        public Nullable<short> col_144 { get; set; }
        public Nullable<short> col_145 { get; set; }
        public Nullable<short> col_146 { get; set; }
        public Nullable<short> col_147 { get; set; }
        public Nullable<short> col_148 { get; set; }
        public Nullable<short> col_149 { get; set; }
        public Nullable<short> col_150 { get; set; }
        public Nullable<short> col_151 { get; set; }
        public Nullable<short> col_152 { get; set; }
        public Nullable<short> col_153 { get; set; }
        public Nullable<short> col_154 { get; set; }
        public Nullable<short> col_155 { get; set; }
        public Nullable<short> col_156 { get; set; }
        public Nullable<short> col_157 { get; set; }
        public Nullable<short> col_158 { get; set; }
        public Nullable<short> col_159 { get; set; }
        public Nullable<short> col_160 { get; set; }
        public Nullable<short> col_161 { get; set; }
        public Nullable<short> col_162 { get; set; }
        public Nullable<short> col_163 { get; set; }
        public Nullable<short> col_164 { get; set; }
        public Nullable<short> col_165 { get; set; }
        public Nullable<short> col_166 { get; set; }
        public Nullable<short> col_167 { get; set; }
        public Nullable<short> col_168 { get; set; }
        public Nullable<short> col_169 { get; set; }
        public Nullable<short> col_170 { get; set; }
        public Nullable<short> col_171 { get; set; }
        public Nullable<short> col_172 { get; set; }
        public Nullable<short> col_173 { get; set; }
        public Nullable<short> col_174 { get; set; }
        public Nullable<short> col_175 { get; set; }
        public Nullable<short> col_176 { get; set; }
        public Nullable<short> col_177 { get; set; }
        public Nullable<short> col_178 { get; set; }
        public Nullable<short> col_179 { get; set; }
        public Nullable<short> col_180 { get; set; }
        public Nullable<short> col_181 { get; set; }
        public Nullable<short> col_182 { get; set; }
        public Nullable<short> col_183 { get; set; }
        public Nullable<short> col_184 { get; set; }
        public Nullable<short> col_185 { get; set; }
        public Nullable<short> col_186 { get; set; }
        public Nullable<short> col_187 { get; set; }
        public Nullable<short> col_188 { get; set; }
        public Nullable<short> col_189 { get; set; }
        public Nullable<short> col_190 { get; set; }
        public Nullable<short> col_191 { get; set; }
        public Nullable<short> col_192 { get; set; }
        public Nullable<short> col_193 { get; set; }
        public Nullable<short> col_194 { get; set; }
        public Nullable<short> col_195 { get; set; }
        public Nullable<short> col_196 { get; set; }
        public Nullable<short> col_197 { get; set; }
        public Nullable<short> col_198 { get; set; }
        public Nullable<short> col_199 { get; set; }
        public Nullable<short> col_200 { get; set; }
        public Nullable<short> col_201 { get; set; }
        public Nullable<short> col_202 { get; set; }
        public Nullable<short> col_203 { get; set; }
        public Nullable<short> col_204 { get; set; }
        public Nullable<short> col_205 { get; set; }
        public Nullable<short> col_206 { get; set; }
        public Nullable<short> col_207 { get; set; }
        public Nullable<short> col_208 { get; set; }
        public Nullable<short> col_209 { get; set; }
        public Nullable<short> col_210 { get; set; }
        public Nullable<short> col_211 { get; set; }
        public Nullable<short> col_212 { get; set; }
        public Nullable<short> col_213 { get; set; }
        public Nullable<short> col_214 { get; set; }
        public Nullable<short> col_215 { get; set; }
        public Nullable<short> col_216 { get; set; }
        public Nullable<short> col_217 { get; set; }
        public Nullable<short> col_218 { get; set; }
        public Nullable<short> col_219 { get; set; }
        public Nullable<short> col_220 { get; set; }
        public Nullable<short> col_221 { get; set; }
        public Nullable<short> col_222 { get; set; }
        public Nullable<short> col_223 { get; set; }
        public Nullable<short> col_224 { get; set; }
        public Nullable<short> col_225 { get; set; }
        public Nullable<short> col_226 { get; set; }
        public Nullable<short> col_227 { get; set; }
        public Nullable<short> col_228 { get; set; }
        public Nullable<short> col_229 { get; set; }
        public Nullable<short> col_230 { get; set; }
        public Nullable<short> col_231 { get; set; }
        public Nullable<short> col_232 { get; set; }
        public Nullable<short> col_233 { get; set; }
        public Nullable<short> col_234 { get; set; }
        public Nullable<short> col_235 { get; set; }
        public Nullable<short> col_236 { get; set; }
        public Nullable<short> col_237 { get; set; }
        public Nullable<short> col_238 { get; set; }
        public Nullable<short> col_239 { get; set; }
        public Nullable<short> col_240 { get; set; }
        public Nullable<short> col_241 { get; set; }
        public Nullable<short> col_242 { get; set; }
        public Nullable<short> col_243 { get; set; }
        public Nullable<short> col_244 { get; set; }
        public Nullable<short> col_245 { get; set; }
        public Nullable<short> col_246 { get; set; }
        public Nullable<short> col_247 { get; set; }
        public Nullable<short> col_248 { get; set; }
        public Nullable<short> col_249 { get; set; }
        public Nullable<short> col_250 { get; set; }
        public Nullable<short> col_251 { get; set; }
        public Nullable<short> col_252 { get; set; }
        public Nullable<short> col_253 { get; set; }
        public Nullable<short> col_254 { get; set; }
        public Nullable<short> col_255 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataset_mapset> dataset_mapset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_type_mapping> doc_type_mapping { get; set; }
    }
}
