//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcsEnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class legacy_file_info
    {
        public long file_id { get; set; }
        public bool deleted { get; set; }
        public string legacy_file_id { get; set; }
        public string legacy_file_type { get; set; }
        public Nullable<int> version_number { get; set; }
        public int seq { get; set; }
        public string legacy_rotation { get; set; }
    
        public virtual file file { get; set; }
    }
}
