//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcsEnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public long id { get; set; }
        public Nullable<long> obsolete_file_id { get; set; }
        public string legacy_note_type { get; set; }
        public Nullable<long> obsolete_note_type_num { get; set; }
        public Nullable<System.DateTime> note_datetime { get; set; }
        public string note_text { get; set; }
        public Nullable<int> legacy_page_number { get; set; }
        public Nullable<int> legacy_pos_x { get; set; }
        public Nullable<int> legacy_pos_y { get; set; }
        public Nullable<int> obsolete_len_x { get; set; }
        public Nullable<int> obsolete_len_y { get; set; }
        public Nullable<long> obsolete_seq { get; set; }
        public Nullable<long> doc_id { get; set; }
    
        public virtual document document { get; set; }
    }
}
