//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcsEnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class onbase_file_info
    {
        public long id { get; set; }
        public long file_id { get; set; }
        public long onbase_doc_id { get; set; }
        public int seq { get; set; }
        public Nullable<int> ob_imagetype { get; set; }
    
        public virtual file file { get; set; }
        public virtual onbase_document onbase_document { get; set; }
    }
}
