//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcsEnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class onbase_key_type
    {
        public short id { get; set; }
        public string name { get; set; }
        public Nullable<long> ob_datatype { get; set; }
        public Nullable<long> ob_keytypelen { get; set; }
        public Nullable<long> ob_keytypenum_prod { get; set; }
        public Nullable<long> ob_keytypenum_test { get; set; }
    }
}
