//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcsEnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class onbase_note
    {
        public long onbase_note_id { get; set; }
        public Nullable<int> len_x { get; set; }
        public Nullable<int> len_y { get; set; }
        public Nullable<System.DateTime> note_datetime { get; set; }
        public Nullable<int> page_number { get; set; }
        public int note_type_num { get; set; }
        public Nullable<int> pos_x { get; set; }
        public Nullable<int> pos_y { get; set; }
        public string note_text { get; set; }
        public Nullable<long> onbase_doc_id { get; set; }
    
        public virtual onbase_document onbase_document { get; set; }
    }
}
